apiVersion: apps/v1
kind: Deployment
metadata:
  name: arsenelearning
  labels:
    app: arsenelearning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arsenelearning
  template:
    metadata:
      labels:
        app: arsenelearning
    spec:
      containers:
        - name: arsenelearning
          image: indamutsa/arsenelearning
          imagePullPolicy: Always
          ports:
            - containerPort: 8080